volumes:
  pgdata:
  
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      postgres_db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      - backend

  postgres_db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5433
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 3s


