const BalanceSheetFields = {
  accumulatedDepreciationAmortizationPPE:
    "Accumulated Depreciation/Amortization PPE",
  capitalLeaseObligations: "Capital Lease Obligations",
  cashAndCashEquivalentsAtCarryingValue: "Cash & Cash Equivalents",
  cashAndShortTermInvestments: "Cash & Short-Term Investments",
  commonStock: "Common Stock",
  commonStockSharesOutstanding: "Shares Outstanding",
  currentAccountsPayable: "Current Accounts Payable",
  currentNetReceivables: "Current Net Receivables",
  deferredRevenue: "Deferred Revenue",
  fiscalDateEnding: "Fiscal Date Ending",
  goodwill: "Goodwill",
  intangibleAssets: "Intangible Assets",
  intangibleAssetsExcludingGoodwill: "Intangible Assets (Excl. Goodwill)",
  inventory: "Inventory",
  longTermDebt: "Long-Term Debt",
  longTermInvestments: "Long-Term Investments",
  otherCurrentAssets: "Other Current Assets",
  otherCurrentLiabilities: "Other Current Liabilities",
  otherNonCurrentLiabilities: "Other Non-Current Liabilities",
  propertyPlantEquipment: "Property, Plant & Equipment",
  retainedEarnings: "Retained Earnings",
  shortLongTermDebtTotal: "Short + Long-Term Debt Total",
  shortTermDebt: "Short-Term Debt",
  shortTermInvestments: "Short-Term Investments",
  totalAssets: "Total Assets",
  totalCurrentAssets: "Total Current Assets",
  totalCurrentLiabilities: "Total Current Liabilities",
  totalLiabilities: "Total Liabilities",
  totalNonCurrentAssets: "Total Non-Current Assets",
  totalNonCurrentLiabilities: "Total Non-Current Liabilities",
  totalShareholderEquity: "Total Shareholder Equity",
  treasuryStock: "Treasury Stock",
};

export default BalanceSheetFields;