const CashFlowStatementFields = {
    operatingCashflow: "Operating Cash Flow",
    paymentsForOperatingActivities: "Payments for Operating Activities",
    proceedsFromOperatingActivities: "Proceeds from Operating Activities",
    changeInOperatingLiabilities: "Change in Operating Liabilities",
    changeInOperatingAssets: "Change in Operating Assets",
    depreciationDepletionAndAmortization: "Depreciation, Depletion & Amortization",
    capitalExpenditures: "Capital Expenditures",
    changeInReceivables: "Change in Receivables",
    changeInInventory: "Change in Inventory",
    profitLoss: "Profit / Loss",
    cashflowFromInvestment: "Cash Flow from Investment",
    cashflowFromFinancing: "Cash Flow from Financing",
    proceedsFromRepaymentsOfShortTermDebt: "Proceeds from Repayments of Short-Term Debt",
    paymentsForRepurchaseOfCommonStock: "Payments for Repurchase of Common Stock",
    paymentsForRepurchaseOfEquity: "Payments for Repurchase of Equity",
    paymentsForRepurchaseOfPreferredStock: "Payments for Repurchase of Preferred Stock",
    dividendPayout: "Dividend Payout",
    dividendPayoutCommonStock: "Dividend Payout - Common Stock",
    dividendPayoutPreferredStock: "Dividend Payout - Preferred Stock",
    proceedsFromIssuanceOfCommonStock: "Proceeds from Issuance of Common Stock",
    proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet: "Proceeds from Issuance of Long-Term Debt & Capital Securities",
    proceedsFromIssuanceOfPreferredStock: "Proceeds from Issuance of Preferred Stock",
    proceedsFromRepurchaseOfEquity: "Proceeds from Repurchase of Equity",
    proceedsFromSaleOfTreasuryStock: "Proceeds from Sale of Treasury Stock",
    changeInCashAndCashEquivalents: "Change in Cash & Cash Equivalents",
    changeInExchangeRate: "Change in Exchange Rate",
    netIncome: "Net Income",
    fiscalDateEnding: "Fiscal Date Ending",
  };
  
  export default CashFlowStatementFields;